/**
 * Constants for conservation package
 */

export const DEFAULT_OBFUSCATION_RADIUS = 2000; // 2km

export const CONSERVATION_STATUS_COLORS = {
  LEAST_CONCERN: '#4CAF50',
  NEAR_THREATENED: '#8BC34A',
  VULNERABLE: '#FFEB3B',
  ENDANGERED: '#FF9800',
  CRITICALLY_ENDANGERED: '#F44336',
  EXTINCT_IN_WILD: '#9C27B0',
  EXTINCT: '#000000',
  DATA_DEFICIENT: '#9E9E9E',
  NOT_EVALUATED: '#BDBDBD',
}; 